---
- name: Creates directory
  file:
    path: ~/project
    state: directory

- name: Copy index test page
  shell: /
    tar -xzvf artifact.tar.gz -C ~/project

- name: Executing node
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
